groups:
  - name: recipe-sharing-website
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status="500"}[5m]) > 0.05
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "More than 5% of requests are failing with status 500 over the last 10 minutes."

      - alert: HighLatency
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High latency detected"
          description: "95th percentile of request duration is greater than 1 second over the last 5 minutes."

      - alert: ServiceDown
        expr: up{job="recipe-sharing-website"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Service is down"
          description: "The recipe-sharing website service is not responding."