apiVersion: v1
kind: Service
metadata:
  name: recipe-sharing-service
  labels:
    app: recipe-sharing
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: recipe-sharing