apiVersion: v1
kind: Service
metadata:
  name: recipe-sharing-service
spec:
  type: NodePort
  selector:
    app: recipe-sharing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 
